#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
# python manage.py runserver_plus 0.0.0.0:8000
uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
