# Generated by Django 3.0.10 on 2020-09-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
