# Generated by Django 3.0.10 on 2020-11-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0005_question_questionpaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="name",
            field=models.TextField(default="test name"),
            preserve_default=False,
        ),
    ]
