# Generated by Django 3.0.10 on 2020-11-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0006_questionpaper_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max_marks",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
