# Generated by Django 3.0.10 on 2020-11-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0007_question_max_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioncategory",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="examination.Subject",
            ),
            preserve_default=False,
        ),
    ]
