# Generated by Django 3.0.10 on 2020-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0009_userquestionmarktracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquestionmarktracker",
            name="mark",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
