# Generated by Django 3.0.10 on 2020-11-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0012_auto_20201110_0416"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "default_related_name": "related_questions",
                "ordering": ["created"],
            },
        ),
        migrations.AlterModelOptions(
            name="questioncategory",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="questionpaper",
            options={
                "default_related_name": "related_question_papers",
                "ordering": ["created"],
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="userquestionmarktracker",
            options={
                "default_related_name": "related_mark_trackers",
                "ordering": ["created"],
            },
        ),
    ]
