# Generated by Django 3.0.10 on 2020-09-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"default_related_name": "related_users"},
        ),
        migrations.AddField(
            model_name="user",
            name="linked_subjects",
            field=models.ManyToManyField(
                related_name="related_users", to="examination.Subject"
            ),
        ),
    ]
